### ISSUE TITLE
h2 tag not rendering on topic weight blog post

### ISSUE THREAD

**Issue by daharmattan1** [Fluxuous/daharmattan1#1]
![image](https://cloud.githubusercontent.com/assets/10886896/9538819/ac87485c-4d16-11e5-9088-c71e706e14ca.png)

**Comment by daharmattan1** [comment]
have no idea why i cant get it to work

**Comment by Fluxuous** [comment]
fixed it.   you needed a line break after the ## tag.

**Comment by daharmattan1** [comment]
cool ty
